# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# the build.os and build.tools section is mandatory
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: doc/source/conf.py

formats:
    - htmlzip

python:
  install:
    - requirements: requirements.txt
    - requirements: doc/requirements.txt
    - method: pip
      path: .
