name: pysteps
channels:
- conda-forge
- defaults
dependencies:
  - python=3.7
  - attrdict
  - jsmin
  - jsonschema
  - matplotlib-base
  - netCDF4
  - numpy
  - opencv
  - pillow
  - pyproj
  - scipy
