#!/usr/bin/env python3
"""
Generate requirements.txt and environment.yml files from pyproject.toml.

This script reads the dependencies from pyproject.toml (the single source of truth)
and generates the requirements files for backwards compatibility and convenience.

Usage:
    python scripts/generate_requirements.py
"""

import re
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    # Python < 3.11
    try:
        import tomli as tomllib
    except ImportError:
        print(
            "Error: tomli package required for Python < 3.11\n"
            "Install with: pip install tomli"
        )
        sys.exit(1)


def parse_version_constraint(spec):
    """
    Convert PEP 440 version constraints to conda-style constraints.
    
    Examples:
        ">=1.24.0,<3.0" -> ">=1.24.0,<3.0"
        ">=4.0.0,<5.0" -> ">=4.0.0,<5.0"
    """
    return spec


def dependency_to_conda_format(dep):
    """
    Convert a PEP 508 dependency string to conda format.
    
    Handles platform markers and converts package names where needed.
    """
    # Remove platform markers for conda (conda handles this differently)
    dep = re.sub(r'\s*;\s*.*$', '', dep)
    
    # Special package name mappings for conda
    package_mappings = {
        'opencv-python': 'opencv',
        'PyWavelets': 'pywavelets',
    }
    
    for pip_name, conda_name in package_mappings.items():
        if dep.startswith(pip_name):
            dep = dep.replace(pip_name, conda_name, 1)
    
    return dep


def generate_requirements_txt(pyproject_data, output_file, include_dev=False):
    """Generate requirements.txt from pyproject.toml."""
    dependencies = pyproject_data.get("project", {}).get("dependencies", [])
    
    lines = [
        "# This file is auto-generated from pyproject.toml",
        "# To regenerate, run: python scripts/generate_requirements.py",
        "# DO NOT EDIT THIS FILE MANUALLY",
        "",
    ]
    
    # Add core dependencies
    for dep in dependencies:
        lines.append(dep)
    
    if include_dev:
        lines.append("")
        lines.append("# Development dependencies")
        dev_deps = (
            pyproject_data.get("project", {})
            .get("optional-dependencies", {})
            .get("dev", [])
        )
        for dep in dev_deps:
            lines.append(dep)
    
    lines.append("")  # Final newline
    
    output_file.write_text("\n".join(lines))
    print(f"✓ Generated {output_file}")


def generate_environment_yml(pyproject_data, output_file, include_dev=False):
    """Generate environment.yml from pyproject.toml."""
    dependencies = pyproject_data.get("project", {}).get("dependencies", [])
    python_version = pyproject_data.get("project", {}).get("requires-python", ">=3.11")
    
    # Extract minimum Python version
    python_min = re.search(r'>=(\d+\.\d+)', python_version)
    if python_min:
        python_spec = f">={python_min.group(1)}"
    else:
        python_spec = ">=3.11"
    
    env_name = "pysteps_dev" if include_dev else "pysteps"
    
    lines = [
        "# This file is auto-generated from pyproject.toml",
        "# To regenerate, run: python scripts/generate_requirements.py",
        "# DO NOT EDIT THIS FILE MANUALLY",
        f"name: {env_name}",
        "channels:",
        "  - conda-forge",
        "  - defaults",
        "dependencies:",
        f"  - python{python_spec}",
    ]
    
    # Add core dependencies
    for dep in dependencies:
        conda_dep = dependency_to_conda_format(dep)
        lines.append(f"  - {conda_dep}")
    
    if include_dev:
        # Add development dependencies
        optional_deps = (
            pyproject_data.get("project", {})
            .get("optional-dependencies", {})
        )
        
        dev_deps = optional_deps.get("dev", [])
        for dep in dev_deps:
            # Skip duplicates already in core dependencies
            dep_name = re.match(r'^([a-zA-Z0-9_-]+)', dep).group(1)
            if not any(d.startswith(dep_name) for d in dependencies):
                conda_dep = dependency_to_conda_format(dep)
                lines.append(f"  - {conda_dep}")
    
    lines.append("")  # Final newline
    
    output_file.write_text("\n".join(lines))
    print(f"✓ Generated {output_file}")


def main():
    """Main function to generate all requirement files."""
    # Get project root directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    pyproject_file = project_root / "pyproject.toml"
    
    if not pyproject_file.exists():
        print(f"Error: {pyproject_file} not found")
        sys.exit(1)
    
    # Read pyproject.toml
    with open(pyproject_file, "rb") as f:
        pyproject_data = tomllib.load(f)
    
    # Generate requirements files
    print("\nGenerating requirement files from pyproject.toml...")
    print("=" * 60)
    
    # requirements.txt
    generate_requirements_txt(
        pyproject_data,
        project_root / "requirements.txt",
        include_dev=False
    )
    
    # requirements_dev.txt
    generate_requirements_txt(
        pyproject_data,
        project_root / "requirements_dev.txt",
        include_dev=True
    )
    
    # environment.yml
    generate_environment_yml(
        pyproject_data,
        project_root / "environment.yml",
        include_dev=False
    )
    
    # environment_dev.yml
    generate_environment_yml(
        pyproject_data,
        project_root / "environment_dev.yml",
        include_dev=True
    )
    
    print("=" * 60)
    print("✓ All requirement files generated successfully!")
    print("\nNote: These files are auto-generated. To update dependencies,")
    print("      edit pyproject.toml and re-run this script.")


if __name__ == "__main__":
    main()
