# Definition of the metadata
# https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html

# More info in environmental variables:
# https://docs.conda.io/projects/conda-build/en/latest/source/environment-variables.html#git-environment-variables



# Specifies package information.
# https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html
package:
    name: pysteps
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1)}}
    # Get the version from the github tag



# Specifies build information.
# https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#build-section
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../


## Specifies where the source code of the package is coming from.
## https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#source-section
#source:
#    path: ../



# Specifies the build and runtime requirements.
# Dependencies of these requirements are included automatically.
# https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#requirements-section
requirements:
  build:
    - python {{ python }}
    - numpy
    - cython
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - numpy
    - cython
    - attrdict
    - jsmin
    - scipy
    - matplotlib
    - jsonschema
  run:
    - python {{ python }}
    - attrdict
    - jsmin
    - jsonschema
    - matplotlib
    - netCDF4
    - numpy
    - opencv
    - pillow
    - pyproj
    - scipy



# Run minimal test for now
test:
  imports:
    - pysteps



# Specifies identifying information about the package.
# https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#about-section
about:
  home: https://pysteps.github.io/
  license: GNU General Public License v3.0
  license_file: LICENSE