"""
pysteps.nowcasts.anvils
=======================

Implements ANVIL-S, which is a stochastic extension of the autoregressive
nowcasting using VIL (ANVIL) nowcasting method developed in :cite:`PCLH2020`.
Ensembles are generated by adding perturbations to the advection and forecast
fields.

.. autosummary::
    :toctree: ../generated/

    forecast
"""
