"""
pysteps.nowcasts.linda
======================

This module implements the Lagrangian INtegro-Difference equation model with
Autoregression (LINDA). The model combines elements from extrapolation,
S-PROG, STEPS and ANVIL, cell tracking and integro-difference equation (IDE)
models with the aim of producing improved nowcasts for convective events. It
consists of the following components:

1. feature detection to identify rain cells
2. advection-based nowcast
3. autoregressive integrated (ARI) process to predict growth and decay
4. convolution to account for loss of predictability
5. stochastic perturbations to simulate forecast errors

Focusing on convective cells, LINDA uses a sparse representation of the input
data. The cells are identified using a blob detection method :cite:`?`. The
advection field is determined using based on the detected blobs, and the
remaining components of the model are applied in the Lagrangian coordinates.
Using the ARI process is adapted from ANVIL :cite:`PCLH2020`, and the
convolution is adapted from the integro-difference equation (IDE)
methodology developed in :cite:`?`. Combination of these two approaches
essentially replaces the cascade decomposition used in S-PROG and STEPS.
Using the convolution has several advantages such as the ability to handle
anisotropic structure, domain boundaries and missing data.

All components of the model are localized at the identified rain cells. The
advection field is determined using the sparse Lucas-Kanade method and
interpolated to cover the whole domain. The convolution is implemented by using
a spatially variable kernel that can describe anisotropic structure. Based on
the marginal distribution and covariance structure of forecast errors, localized
perturbations are generated by adapting the SSFT methodology developed in
:cite:`NBSG2017`.

.. autosummary::
    :toctree: ../generated/

    forecast
"""


def forecast():
    pass
